# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f73de234189050fc39f394c7ba2bf5054e6f0963d76f95977dfa512e4594f9a93bbbe75fab5ae3ad5987ab8dedc9275b66aeda3fff4f0a31daa4a3c45ac6fbf

test:
  secret_key_base: cccac6fa83abbb07e08255539dc46fee45583c464d7d42ef8a012e8b6676ec7c30f19d9752d0bfd039640ee7d246c06def2cfc1f6d6058247bcc9ae4cc8c30bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
